# Generated by Django 5.1.3 on 2024-11-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accouting', '0003_delete_expense_delete_income_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
