# Generated by Django 4.2.17 on 2024-12-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accouting', '0006_alter_transaction_options_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Travel', 'Travel'), ('Shopping', 'Shopping')], max_length=50),
        ),
    ]
